server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver # TODO: there should be changed if you're using MySQL instead of MariaDB
    url: jdbc:mariadb://localhost:3306/chat138db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
    username: nanami
    password: UmitsukinoKokuuniSuzushiHototogisu # TODO: change here
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b


pagehelper:
  reasonable: true
mybatis:
  type-aliases-package: moe.zzy040330.chat138.entity
  mapper-locations: classpath*:mapper/*.xml
